export * from "./ATag.js";
export * from "./TagInt.js";
export * from "./TagString.js";
export * from "./TagShort.js";
export * from "./TagTiny.js";
export * from "./TagLong.js";
export * from "./TagBoolean.js";
export * from "./TagFloat.js";
// export * from "./TagDouble.js";
export * from "./TagList.js";
export * from "./TagCompound.js";
export * from "./TagCharacter.js";
export * from "./TagUUID.js";
